name: 🚚 Деплой релиза в продакшн

on:
  workflow_dispatch:
    inputs:
      release_version:
        type: string
        description: "Release version"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      YC_REGISTRY_ID: ${{ secrets.YC_REGISTRY_ID }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SERVER_HOST: 158.160.191.214
      SERVER_USER: lomt1k

    steps:
      - name: 🔍 Проверить наличие Docker-образа
        run: |
          echo "Убедитесь, что образ cr.yandex://${YC_REGISTRY_ID}://${APP_NAME}:${{ github.event.inputs.release_version }}_latest есть в Container Registry"

      - name: 🚚 Деплой на сервер через SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ env.SERVER_USER }}
          key: ${{ env.SSH_KEY }}
          script: |
            docker pull cr.yandex/${{ env.YC_REGISTRY_ID }}/app:${{ github.event.inputs.release_version }}_latest
            docker stop shri-infra || true
            docker rm shri-infra || true
            docker run -d --name shri-infra -p 3000:3000 cr.yandex/${{ env.YC_REGISTRY_ID }}/app:${{ github.event.inputs.release_version }}_latest

      - name: 🔁 Checkout кода
        uses: actions/checkout@v4

      - name: 💬 Оставить комментарий в Issue
        run: |
          gh issue comment \
            $(gh issue list --search "Release v${{ github.event.inputs.release_version }}" --json number --jq '.[0].number') \
            --body $'🚀 Релиз v'"${{ github.event.inputs.release_version }}"$' выкачен в прод\n'"$(date)"$'\n🧑‍💻 Автор: '"${{ github.actor }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}