name: 🚀 Выкатка релиза в прод

on:
  workflow_dispatch:
    inputs:
      release_version:
        type: string
        description: "Версия релиза для выливки в продакшн"
        required: true

jobs:
  deploy_to_prod:
    name: 📦 Выливка v${{ github.workflow.inputs.release_version }} в прод
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: write
      issues: write

    env:
      REGISTRY_URL: cr.yandex
      APP_NAME: app
      YC_REGISTRY_ID: ${{ secrets.YC_REGISTRY_ID }}
      RELEASE_VERSION: ${{ github.workflow.inputs.release_version }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SERVER_HOST: 158.160.191.214
      SERVER_USER: lomt1k

    steps:
      - name: 🔍 Checkout кода
        uses: actions/checkout@v4

      - name: 🧪 Проверка наличия Docker-образа в Container Registry
        run: |
          echo "Проверяем наличие образа: ${REGISTRY_URL}/${YC_REGISTRY_ID}/${APP_NAME}:${RELEASE_VERSION}_latest"

          # Авторизация
          echo "${{ secrets.YC_OAUTH_TOKEN }}" | docker login --username oauth --password-stdin ${REGISTRY_URL}

          # Попытка скачать манифест (для проверки существования)
          if ! crane manifest ${REGISTRY_URL}/${YC_REGISTRY_ID}/${APP_NAME}:${RELEASE_VERSION}_latest > /dev/null 2>&1; then
            echo "❌ Образ ${REGISTRY_URL}/${YC_REGISTRY_ID}/${APP_NAME}:${RELEASE_VERSION}_latest не найден!"
            exit 1
          else
            echo "✅ Образ найден — можно продолжать деплой."
          fi

      - name: 🚚 Деплой на сервер через SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ env.SERVER_USER }}
          key: ${{ env.SSH_KEY }}
          script: |
            echo "🔍 Обновляем локальный образ"
            docker pull ${REGISTRY_URL}/${YC_REGISTRY_ID}/${APP_NAME}:${RELEASE_VERSION}_latest

            echo "🛑 Останавливаем старый контейнер"
            docker stop shri-infra || true

            echo "🗑 Удаляем старый контейнер"
            docker rm shri-infra || true

            echo "🚀 Запускаем новый контейнер"
            docker run -d \
              --name shri-infra \
              -p 3000:3000 \
              ${REGISTRY_URL}/${YC_REGISTRY_ID}/${APP_NAME}:${RELEASE_VERSION}_latest

      - name: 🧾 Добавление комментария к Issue о выкатке
        uses: actions/github-script@v6
        with:
          script: |
            const body = `
              🚀 Релиз v${{ env.RELEASE_VERSION }} выкачен в прод
              📅 Дата: ${new Date().toISOString()}
              👨‍💻 Автор: ${{ github.actor }}
              🌐 Адрес приложения: http://${{ env.SERVER_HOST }}:3000/hw/store
            `;

            // Ищем Issue по заголовку
            const { data: issues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              creator: 'github-actions[bot]',
              state: 'all',
              per_page: 100,
              labels: ''
            });

            const targetIssue = issues.find(issue => issue.title.includes("🚀 Выпуск релиза v${{ env.RELEASE_VERSION }}"));

            if (targetIssue) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: targetIssue.number,
                body: body
              });
            } else {
              console.log('Не найдено Issue для релиза v${{ env.RELEASE_VERSION }}');
            }